name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run tests with coverage
        run: flutter test --coverage
        
      - name: Verify coverage file
        run: |
          if [ ! -f ./coverage/lcov.info ]; then
            echo "Coverage file not found!"
            exit 1
          fi
          echo "Coverage file size: $(wc -l < ./coverage/lcov.info) lines"
          head -n 5 ./coverage/lcov.info
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: vento007/tiny_db
          verbose: true 